version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - '${DEV_DATA:-./dev}/database:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 1s
      timeout: 10s
      retries: 30
